### ISSUE TITLE
NodeJS container failed again on `rdkafka`

### ISSUE THREAD

**Issue by phracek** [sclorg/s2i-nodejs-container#365] opened 2022-10-20 10:19 UTC
The failed logs can be seen here:
* https://artifacts.dev.testing-farm.io/9742a372-c39c-4968-87a6-b292a0f90440/ for CentOS Stream 9
* https://artifacts.dev.testing-farm.io/7bc23ccc-b2f9-425f-b1a7-4a6d174c8ce9/ for NodeJS 14 Fedora
* https://artifacts.dev.testing-farm.io/e7b3853c-61b8-446c-a5f7-b5d152581d70/ for NodeJS 16 Fedora
* https://artifacts.dev.testing-farm.io/d306391c-de72-4958-898b-bd273d18b102/ for NodeJS 18 Fedora

```bash
++ -MD -MP -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wno-non-virtual-dtor -c HeadersImpl.cpp -o HeadersImpl.o
g++ -MD -MP -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wno-non-virtual-dtor -c QueueImpl.cpp -o QueueImpl.o
g++ -MD -MP -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wno-non-virtual-dtor -c MetadataImpl.cpp -o MetadataImpl.o
Creating shared library librdkafka++.so.1
g++ -L/opt/app-root/src/node_modules/node-rdkafka/build/deps -shared -Wl,-soname,librdkafka++.so.1 RdKafka.o ConfImpl.o HandleImpl.o ConsumerImpl.o ProducerImpl.o KafkaConsumerImpl.o TopicImpl.o TopicPartitionImpl.o MessageImpl.o HeadersImpl.o QueueImpl.o MetadataImpl.o -o librdkafka++.so.1 -L../src -lrdkafka
cp librdkafka++.so.1 librdkafka++-dbg.so.1
Creating static library librdkafka++.a
ar rcs librdkafka++.a RdKafka.o ConfImpl.o HandleImpl.o ConsumerImpl.o ProducerImpl.o KafkaConsumerImpl.o TopicImpl.o TopicPartitionImpl.o MessageImpl.o HeadersImpl.o QueueImpl.o MetadataImpl.o
cp librdkafka++.a librdkafka++-dbg.a
Creating librdkafka++.so symlink
rm -f "librdkafka++.so" && ln -s "librdkafka++.so.1" "librdkafka++.so"
Generating pkg-config file rdkafka++.pc
Generating pkg-config file rdkafka++-static.pc
Checking librdkafka++ integrity
librdkafka++.so.1              OK
librdkafka++.a                 OK
make[2]: Leaving directory '/opt/app-root/src/node_modules/node-rdkafka/deps/librdkafka/src-cpp'
make[2]: Entering directory '/opt/app-root/src/node_modules/node-rdkafka/deps/librdkafka/src'
Install librdkafka to /opt/app-root/src/node_modules/node-rdkafka/build/deps
d $DESTDIR/opt/app-root/src/node_modules/node-rdkafka/build/deps/include/librdkafka
[91m/bin/sh: line 1: d: command not found
[0m[91mmake[2]: [../mklove/Makefile.base:269: lib-install] Error 127 (ignored)
[0md $DESTDIR/opt/app-root/src/node_modules/node-rdkafka/build/deps
[91m/bin/sh: line 1: d: command not found
[0mrdkafka.h rdkafka_mock.h $DESTDIR/opt/app-root/src/node_modules/node-rdkafka/build/deps/include/librdkafka
[91mmake[2]: [../mklove/Makefile.base:270: lib-install] Error 127 (ignored)
[0m[91m/bin/sh: line 1: rdkafka.h: command not found
[0mmake[2]: Leaving directory '/opt/app-root/src/node_modules/node-rdkafka/deps/librdkafka/src'
[91mmake[2]: *** [../mklove/Makefile.base:271: lib-install] Error 127
[0m[91mmake[1]: *** [Makefile:44: install-subdirs] Error 2
[0mmake[1]: Leaving directory '/opt/app-root/src/node_modules/node-rdkafka/deps/librdkafka'
[91mmake: *** [deps/librdkafka.target.mk:30: 11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate] Error 2
[0mrm 11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate
make: Leaving directory '/opt/app-root/src/node_modules/node-rdkafka/build'
[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mbuild error 
[0m[91mgyp[0m[91m ERR! stack[0m[91m Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
[0m[91mgyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
[0m[91mgyp ERR! [0m[91mSystem Linux 5.19.15-201.fc36.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/app-root/src/node_modules/node-rdkafka
[0m[91mgyp ERR! node -v v14.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
[0m[91mnpm[0m[91m WARN hello-world@0.0.1 No description
[0m[91mnpm[0m[91m [0m[91mWARN[0m[91m hello-world@0.0.1 No repository field.
[0m[91mnpm WARN[0m[91m hello-world@0.0.1 No license field.
[0m[91m
[0m[91mnpm[0m[91m ERR! code ELIFECYCLE
npm ERR! errno 1
[0m[91mnpm ERR! node-rdkafka@2.14.0 install: `node-gyp rebuild`
npm[0m[91m ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-rdkafka@2.14.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0m[91m
[0m[91mnpm ERR! A complete log of this run can be found in:
npm ERR!     /opt/app-root/src/.npm/_logs/2022-10-20T06_26_23_499Z-debug.log
[0mThe command '/bin/sh -c /usr/libexec/s2i/assemble' returned a non-zero code: 1
S2I image 'quay.io/f35/nodejs:14' test FAILED (exit code: 1)
docker: container ID file found, make sure the other container isn't running or delete /tmp/tmp.yYAA7DnE3s.cid.
See 'docker run --help'.
Error response from daemon: Cannot kill container: 7fc677cf787b8190a9933b34452f5d4fdab9568f27dff69351630f1e432ec9f9: No such container: 7fc677cf787b8190a9933b34452f5d4fdab9568f27dff69351630f1e432ec9f9
Success!
Untagged: quay.io/f35/nodejs
```

**Comment by phracek** [comment] 2022-10-20 10:29
@mhdawson Can you please help us with what's going on? I don't follow what is missing or wrong.
```bash
Install librdkafka to /opt/app-root/src/node_modules/node-rdkafka/build/deps
d $DESTDIR/opt/app-root/src/node_modules/node-rdkafka/build/deps/include/librdkafka
�[91m/bin/sh: line 1: d: command not found
�[0m�[91mmake[2]: [../mklove/Makefile.base:269: lib-install] Error 127 (ignored)
�[0md $DESTDIR/opt/app-root/src/node_modules/node-rdkafka/build/deps
�[91m/bin/sh: line 1: d: command not found
�[0mrdkafka.h rdkafka_mock.h $DESTDIR/opt/app-root/src/node_modules/node-rdkafka/build/deps/include/librdkafka
�[91mmake[2]: [../mklove/Makefile.base:270: lib-install] Error 127 (ignored)
�[0m�[91m/bin/sh: line 1: rdkafka.h: command not found
�[0mmake[2]: Leaving directory '/opt/app-root/src/node_modules/node-rdkafka/deps/librdkafka/src'
�[91mmake[2]: *** [../mklove/Makefile.base:271: lib-install] Error 127
�[0m�[91mmake[1]: *** [Makefile:44: install-subdirs] Error 2
�[0mmake[1]: Leaving directory '/opt/app-root/src/node_modules/node-rdkafka/deps/librdkafka'
```

**Comment by phracek** [comment] 2022-10-20 10:30
Issue on `node-rdkafka` is also filed here: https://github.com/Blizzard/node-rdkafka/issues/979

**Comment by mhdawson** [comment] 2022-10-20 21:09
@pacostas could you help out with this one. I think it lines up with some testing you are already doing with Kafkajs and node-rdkafka so you might have a heads start.

**Comment by mhdawson** [comment] 2022-10-20 21:12
@phracek there was a new version of node-rdkafka published 3 days ago. Did this just art failing or is it just failing on the platforms you mentioned or is it the first time we are trying to run the tests there?

**Comment by pacostas** [comment] 2022-10-21 15:58
@mhdawson  Yes, I can validate that until version 2.13 the build succeeds.

**Comment by mhdawson** [comment] 2022-10-21 17:19
@pacostas thanks, that is a good starting point. Does it also fail locally for you or just in the container as part of running the tests?

**Comment by pacostas** [comment] 2022-10-22 14:24
@mhdawson I reproduced the error on the [node 14 fedora](https://github.com/sclorg/s2i-nodejs-container/blob/master/14/Dockerfile.fedora) which is one of the above container images. I'm trying to rebuild latest versions of this package that exist only on github with the hope the issue is fixed in these later commits.

**Comment by phracek** [comment] 2022-10-24 12:22
@pacostas @mhdawson What should be fixed in s2i-nodejs-containers? Or should we wait a couple of days? I saw in the log, that we are using node_rdkafka 1.9.2 and you are talking about node_rdkafka 2.13.  Do we need somehow extend https://github.com/sclorg/s2i-nodejs-container/blob/master/14/s2i/bin/assemble?

**Comment by pacostas** [comment] 2022-10-24 13:30
> @pacostas @mhdawson What should be fixed in s2i-nodejs-containers? Or should we wait a couple of days? I saw in the log, that we are using node_rdkafka 1.9.2 and you are talking about node_rdkafka 2.13. Do we need somehow extend https://github.com/sclorg/s2i-nodejs-container/blob/master/14/s2i/bin/assemble?
> 
> Thanks for solving this issue :)

node-rdkafka does not have version 1.9.2 so probably this version is of [librdkafka](https://github.com/edenhill/librdkafka)

**Comment by pacostas** [comment] 2022-10-25 11:53
There is no `which` command installed on fedora, that is why is failing. By adding the `which` word inside the MODULE_DEPS it succeeds installing node-rdkafka

**Comment by mhdawson** [comment] 2022-10-25 13:08
@pacostas do you know what introduced the need for which? I'm wondering if it was the node-rdkafka wrapper itself or librdkafka that it depends on?

**Comment by pacostas** [comment] 2022-10-25 14:33
@mhdawson  Good question, looks like is on build of librdkafka on this line https://github.com/edenhill/librdkafka/blame/master/mklove/modules/configure.base#L2449 . This was introduced 1 year ago.
It wasnt visible from the final error. It was only visible on the checks, above the error.
Definetely we can open a PR on librdkafka to replace the which or create an alias for it. Although `which` is very basic command.

**Comment by mhdawson** [comment] 2022-10-25 14:34
@pacostas how big is which in terms of bytes?

**Comment by pacostas** [comment] 2022-10-25 14:59
@mhdawson 81 kilobyte
```
Name         : which
Version      : 2.21
Release      : 32.fc36
Architecture : x86_64
Size         : 81 k
Source       : which-2.21-32.fc36.src.rpm
Repository   : @System
From repo    : anaconda
Summary      : Displays where a particular program in your path is located
URL          : https://savannah.gnu.org/projects/which/
License      : GPLv3
Description  : The which command shows the full pathname of a specified program, if
             : the specified program is in your PATH.

```

**Comment by mhdawson** [comment] 2022-10-25 15:01
@pacostas thanks given that I think we should add it to the container.  Can you create a PR to add it to the 14, 16 and 18 containers?

@hhorak, @voxik, @kasicka please comment if you have any concerns in adding it to the containers.

**Comment by pacostas** [comment] 2022-10-25 15:03
@mhdawson I think it has already been added https://github.com/sclorg/s2i-nodejs-container/pull/366

**Comment by hhorak** [comment] 2022-10-25 15:41
We need to pay attention at dependencies as well, but I don't expect which having any other RPM deps. I don't have a strong opinion, but incline to say "let's add it".

**Comment by mhdawson** [comment] 2022-10-25 19:09
@pacostas thanks for pointing that out.

**Comment by hhorak** [comment] 2022-10-26 10:29
Looking at the real example locally:

Without `which`:
```
$ make tag VERSIONS=16-minimal  OS=rhel8
$ podman run -ti --rm quay.io/ubi8/nodejs-16-minimal:1 bash -c 'du -d 0 / 2>/dev/null'
182844	/
```

With `which`:
```
$ make tag VERSIONS=16-minimal  OS=rhel8
$ podman run -ti --rm quay.io/ubi8/nodejs-16-minimal:1 bash -c 'du -d 0 / 2>/dev/null'
182976	/
```

The diff:
```
echo $((182976 - 182844))
132
```

So the difference is really just a bit more than 100kB, so I'd say let's add `which` for the sake of usability.

**Closed** 2022-10-26 14:55 UTC
